/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPurchaserRouteImport } from './routes/_authenticated/purchaser'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboard_test_editRouteImport } from './routes/_authenticated/dashboard_test_edit'
import { Route as AuthenticatedDashboard_test1RouteImport } from './routes/_authenticated/dashboard_test1'
import { Route as AuthenticatedDashboard_testRouteImport } from './routes/_authenticated/dashboard_test'
import { Route as AuthenticatedDashboard_stagingRouteImport } from './routes/_authenticated/dashboard_staging'
import { Route as AuthenticatedDashboard_modRouteImport } from './routes/_authenticated/dashboard_mod'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaserRoute = AuthenticatedPurchaserRouteImport.update({
  id: '/purchaser',
  path: '/purchaser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboard_test_editRoute =
  AuthenticatedDashboard_test_editRouteImport.update({
    id: '/dashboard_test_edit',
    path: '/dashboard_test_edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboard_test1Route =
  AuthenticatedDashboard_test1RouteImport.update({
    id: '/dashboard_test1',
    path: '/dashboard_test1',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboard_testRoute =
  AuthenticatedDashboard_testRouteImport.update({
    id: '/dashboard_test',
    path: '/dashboard_test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboard_stagingRoute =
  AuthenticatedDashboard_stagingRouteImport.update({
    id: '/dashboard_staging',
    path: '/dashboard_staging',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboard_modRoute =
  AuthenticatedDashboard_modRouteImport.update({
    id: '/dashboard_mod',
    path: '/dashboard_mod',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard_mod': typeof AuthenticatedDashboard_modRoute
  '/dashboard_staging': typeof AuthenticatedDashboard_stagingRoute
  '/dashboard_test': typeof AuthenticatedDashboard_testRoute
  '/dashboard_test1': typeof AuthenticatedDashboard_test1Route
  '/dashboard_test_edit': typeof AuthenticatedDashboard_test_editRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/purchaser': typeof AuthenticatedPurchaserRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard_mod': typeof AuthenticatedDashboard_modRoute
  '/dashboard_staging': typeof AuthenticatedDashboard_stagingRoute
  '/dashboard_test': typeof AuthenticatedDashboard_testRoute
  '/dashboard_test1': typeof AuthenticatedDashboard_test1Route
  '/dashboard_test_edit': typeof AuthenticatedDashboard_test_editRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/purchaser': typeof AuthenticatedPurchaserRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboard_mod': typeof AuthenticatedDashboard_modRoute
  '/_authenticated/dashboard_staging': typeof AuthenticatedDashboard_stagingRoute
  '/_authenticated/dashboard_test': typeof AuthenticatedDashboard_testRoute
  '/_authenticated/dashboard_test1': typeof AuthenticatedDashboard_test1Route
  '/_authenticated/dashboard_test_edit': typeof AuthenticatedDashboard_test_editRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/purchaser': typeof AuthenticatedPurchaserRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard_mod'
    | '/dashboard_staging'
    | '/dashboard_test'
    | '/dashboard_test1'
    | '/dashboard_test_edit'
    | '/history'
    | '/profile'
    | '/purchaser'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard_mod'
    | '/dashboard_staging'
    | '/dashboard_test'
    | '/dashboard_test1'
    | '/dashboard_test_edit'
    | '/history'
    | '/profile'
    | '/purchaser'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard_mod'
    | '/_authenticated/dashboard_staging'
    | '/_authenticated/dashboard_test'
    | '/_authenticated/dashboard_test1'
    | '/_authenticated/dashboard_test_edit'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/purchaser'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchaser': {
      id: '/_authenticated/purchaser'
      path: '/purchaser'
      fullPath: '/purchaser'
      preLoaderRoute: typeof AuthenticatedPurchaserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard_test_edit': {
      id: '/_authenticated/dashboard_test_edit'
      path: '/dashboard_test_edit'
      fullPath: '/dashboard_test_edit'
      preLoaderRoute: typeof AuthenticatedDashboard_test_editRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard_test1': {
      id: '/_authenticated/dashboard_test1'
      path: '/dashboard_test1'
      fullPath: '/dashboard_test1'
      preLoaderRoute: typeof AuthenticatedDashboard_test1RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard_test': {
      id: '/_authenticated/dashboard_test'
      path: '/dashboard_test'
      fullPath: '/dashboard_test'
      preLoaderRoute: typeof AuthenticatedDashboard_testRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard_staging': {
      id: '/_authenticated/dashboard_staging'
      path: '/dashboard_staging'
      fullPath: '/dashboard_staging'
      preLoaderRoute: typeof AuthenticatedDashboard_stagingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard_mod': {
      id: '/_authenticated/dashboard_mod'
      path: '/dashboard_mod'
      fullPath: '/dashboard_mod'
      preLoaderRoute: typeof AuthenticatedDashboard_modRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboard_modRoute: typeof AuthenticatedDashboard_modRoute
  AuthenticatedDashboard_stagingRoute: typeof AuthenticatedDashboard_stagingRoute
  AuthenticatedDashboard_testRoute: typeof AuthenticatedDashboard_testRoute
  AuthenticatedDashboard_test1Route: typeof AuthenticatedDashboard_test1Route
  AuthenticatedDashboard_test_editRoute: typeof AuthenticatedDashboard_test_editRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPurchaserRoute: typeof AuthenticatedPurchaserRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboard_modRoute: AuthenticatedDashboard_modRoute,
  AuthenticatedDashboard_stagingRoute: AuthenticatedDashboard_stagingRoute,
  AuthenticatedDashboard_testRoute: AuthenticatedDashboard_testRoute,
  AuthenticatedDashboard_test1Route: AuthenticatedDashboard_test1Route,
  AuthenticatedDashboard_test_editRoute: AuthenticatedDashboard_test_editRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPurchaserRoute: AuthenticatedPurchaserRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
